import type { LucideIcon } from "lucide-react";
import {
  BookOpen, Bot, Cpu, Crown, GraduationCap, Globe2, Handshake, Heart, Home,
  Leaf, Lightbulb, Lock, Server, Sparkles, Users, Wallet,
} from "lucide-react";

export type PlatformNavItem = { label: string; slug?: string };
export type PlatformSection = {
  path: string;
  label: string;
  title: string;
  subtitle: string;
  heading: string;
  icon: LucideIcon;
  items: PlatformNavItem[];
};

const item = (label: string, slug?: string): PlatformNavItem => ({ label, slug });

export const PLATFORM_SECTIONS: PlatformSection[] = [
  { path: "/", label: "Overview", title: "AEON GENESIS OS", subtitle: "The Gospel Economy Operating System", heading: "Platform Overview", icon: Home, items: [] },
  { path: "/gospel-core", label: "Gospel Core", title: "GOSPEL CORE", subtitle: "The Eternal Foundation. The Unchanging Source. The Living Power.", heading: "Gospel Core Overview", icon: BookOpen, items: [item("Identity & Purpose"), item("Grace & Salvation", "grace-salvation"), item("Scripture & Truth", "scripture-truth"), item("Faith & Belief", "faith-belief"), item("Love & Relationship", "love-relationship"), item("Discipleship & Growth", "discipleship-growth"), item("Mission & Purpose", "mission-purpose"), item("Worship & Reverence", "worship-reverence"), item("Kingdom Impact", "kingdom-impact")] },
  { path: "/people", label: "People & Discipleship", title: "PEOPLE & DISCIPLESHIP", subtitle: "Every Person. Every Step. Every Nation.", heading: "Discipleship Journey", icon: Users, items: [item("People Overview"), item("Spiritual Journey", "journey"), item("Groups & Communities", "groups"), item("Mentorship", "mentorship"), item("Discipleship Pathways", "pathways"), item("Training & Resources", "training"), item("Assignments", "assignments"), item("Care & Follow-up", "care"), item("Milestones", "milestones"), item("Testimony & Stories", "testimonies"), item("People Directory", "directory"), item("Communication Hub", "communications"), item("Event Management", "events"), item("Content Library", "content-library"), item("Coaching Center", "coaching"), item("Prayer Network", "prayer-network"), item("Insights & Reports", "insights-reports")] },
  { path: "/education", label: "Education", title: "EDUCATION & LEARNING", subtitle: "Equipping Minds. Shaping Hearts. Transforming Nations.", heading: "Learning Navigation", icon: GraduationCap, items: [item("Dashboard"), item("My Learning", "my-learning"), item("Courses", "courses"), item("Learning Paths", "learning-paths"), item("Certificates", "certificates"), item("Live Classes", "live-classes"), item("Library", "library"), item("Study Groups", "study-groups"), item("Mentorship", "mentorship"), item("Kids Zone", "kids-zone"), item("Educators Hub", "educators-hub")] },
  { path: "/innovation", label: "Innovation", title: "INNOVATION & ENTREPRENEURSHIP", subtitle: "Kingdom Innovation. Marketplace Impact. Eternal Value.", heading: "Innovation Navigation", icon: Lightbulb, items: [item("Innovation Dashboard"), item("Idea Hub", "idea-hub"), item("Opportunity Explorer", "opportunity-explorer"), item("Solution Lab", "solution-lab"), item("Startup Studio", "startup-studio"), item("Venture Builder", "venture-builder"), item("Incubator Programs", "incubator-programs"), item("Accelerator Programs", "accelerator-programs"), item("Patents & IP", "patents-ip"), item("Marketplace", "marketplace"), item("Investors Network", "investors-network"), item("Partnerships", "partnerships"), item("Mentorship Match", "mentorship-match"), item("Resources & Tools", "resources-tools")] },
  { path: "/health", label: "Health & Wellbeing", title: "HEALTH & WELLBEING", subtitle: "Whole-person health for flourishing communities.", heading: "Health Navigation", icon: Heart, items: [item("Health Dashboard"), item("Physical Health", "physical-health"), item("Mental Health", "mental-health"), item("Spiritual Health", "spiritual-health"), item("Nutrition & Lifestyle", "nutrition-lifestyle"), item("Preventive Care", "preventive-care"), item("Community Care", "community-care"), item("Health Records", "health-records"), item("Appointments", "appointments"), item("Telehealth", "telehealth"), item("Care Teams", "care-teams"), item("Resources & Articles", "resources-articles"), item("Challenges & Goals", "challenges-goals")] },
  { path: "/stewardship", label: "Stewardship", title: "STEWARDSHIP & CREATION", subtitle: "Restoring creation. Renewing communities. Sustaining generations.", heading: "Creation Navigation", icon: Leaf, items: [item("Stewardship Dashboard"), item("Climate & Environment", "climate-environment"), item("Ecosystems & Biodiversity", "ecosystems-biodiversity"), item("Water Stewardship", "water-stewardship"), item("Land & Soil Health", "land-soil-health"), item("Renewable Energy", "renewable-energy"), item("Sustainable Communities", "sustainable-communities"), item("Waste & Circular Economy", "waste-circular-economy"), item("Creation Projects", "creation-projects"), item("Resources & Tools", "resources-tools"), item("Scholars & Research", "scholars-research"), item("Policies & Advocacy", "policies-advocacy")] },
  { path: "/impact", label: "Global Impact", title: "GLOBAL IMPACT", subtitle: "Measurable transformation across nations and generations.", heading: "Impact Navigation", icon: Globe2, items: [item("Impact Dashboard"), item("Global Projects", "global-projects"), item("Country Hubs", "country-hubs"), item("Project Categories", "project-categories"), item("SDG Alignment", "sdg-alignment"), item("Impact Partners", "impact-partners"), item("Donor & Funding", "donor-funding"), item("Stories of Change", "stories-change"), item("Reports & Analytics", "reports-analytics"), item("Community Action", "community-action"), item("Volunteers", "volunteers"), item("Pray for the Nations", "pray-nations")] },
  { path: "/intelligence", label: "Data & Intelligence", title: "INTELLIGENCE", subtitle: "The Aeon Brain. Wisdom, insight, and discernment at scale.", heading: "Intelligence Navigation", icon: Sparkles, items: [item("Intelligence Dashboard"), item("Signal Stream", "signal-stream"), item("Predictive Analytics", "predictive-analytics"), item("Knowledge Graph", "knowledge-graph"), item("Model Health", "model-health"), item("Ethics & Safety", "ethics-safety")] },
  { path: "/ai-automation", label: "AI & Automation", title: "AI & AUTOMATION", subtitle: "Intelligent systems that multiply mission impact.", heading: "AI Navigation", icon: Bot, items: [item("AI Dashboard"), item("AI Agents", "ai-agents"), item("Automation Workflows", "automation-workflows"), item("Model Management", "model-management"), item("Prompt Studio", "prompt-studio"), item("AI Integrations", "ai-integrations"), item("RPA Center", "rpa-center"), item("Decision Intelligence", "decision-intelligence"), item("AI Monitoring", "ai-monitoring"), item("AI Governance", "ai-governance"), item("Experiment Lab", "experiment-lab"), item("Knowledge Graph", "knowledge-graph"), item("AI Marketplace", "ai-marketplace")] },
  { path: "/platform", label: "Platform", title: "PLATFORM", subtitle: "A unified digital foundation for global impact.", heading: "Platform Navigation", icon: Cpu, items: [item("Platform Dashboard"), item("System Architecture", "system-architecture"), item("Microservices", "microservices"), item("API Gateway", "api-gateway"), item("Data & Intelligence", "data-intelligence"), item("Security & Trust", "security-trust"), item("Automation & Workflows", "automation-workflows"), item("Integration Hub", "integration-hub"), item("Developer Center", "developer-center"), item("Monitoring & Observability", "monitoring-observability"), item("Performance Analytics", "performance-analytics"), item("Infrastructure", "infrastructure"), item("DevOps & CI/CD", "devops-ci-cd"), item("Release Management", "release-management"), item("Configuration Center", "configuration-center")] },
  { path: "/infrastructure", label: "Infrastructure", title: "INFRASTRUCTURE", subtitle: "Resilient global systems built for scale.", heading: "Infrastructure Navigation", icon: Server, items: [item("Infrastructure Dashboard"), item("Service Topology", "service-topology"), item("Resource Inventory", "resource-inventory"), item("Edge Locations", "edge-locations"), item("Data Centers", "data-centers"), item("Network Map", "network-map"), item("Compute Clusters", "compute-clusters"), item("Storage Systems", "storage-systems"), item("Databases", "databases"), item("Containers & Orchestration", "containers-orchestration"), item("Serverless", "serverless"), item("Backup & DR", "backup-dr"), item("Monitoring & Logs", "monitoring-logs"), item("Cost Management", "cost-management"), item("Policies & Compliance", "policies-compliance")] },
  { path: "/security", label: "Security & Trust", title: "SECURITY & TRUST", subtitle: "Protecting people, data, and mission-critical systems.", heading: "Security Navigation", icon: Lock, items: [item("Security Dashboard"), item("Identity & Access", "identity-access"), item("Zero Trust Network", "zero-trust-network"), item("Data Protection", "data-protection"), item("Threat Detection", "threat-detection"), item("Vulnerability Management", "vulnerability-management"), item("Security Operations", "security-operations"), item("Compliance Center", "compliance-center"), item("Privacy Management", "privacy-management"), item("Security Policies", "security-policies"), item("Audit & Logs", "audit-logs"), item("Incident Response", "incident-response"), item("Business Continuity", "business-continuity"), item("Security Awareness", "security-awareness")] },
  { path: "/partners", label: "Partners", title: "PARTNERS & ORGANIZATIONS", subtitle: "One body. Shared mission. Greater impact.", heading: "Partnership Navigation", icon: Handshake, items: [item("Partners Dashboard"), item("Partner Directory", "partner-directory"), item("Organization Hub", "organization-hub"), item("Network Map", "network-map"), item("Partnership Opportunities", "partnership-opportunities"), item("Active Collaborations", "active-collaborations"), item("Resource Exchange", "resource-exchange"), item("Co-Innovation Lab", "co-innovation-lab"), item("Funding & Grants", "funding-grants"), item("Events & Webinars", "events-webinars"), item("News & Updates", "news-updates"), item("Partner Insights", "partner-insights")] },
  { path: "/funding", label: "Funding", title: "FUNDING & RESOURCES", subtitle: "Fueling kingdom vision with transparent stewardship.", heading: "Funding Hub", icon: Wallet, items: [item("Overview Dashboard"), item("Funding Opportunities", "funding-opportunities"), item("Grants Directory", "grants-directory"), item("Investors & Donors", "investors-donors"), item("Resource Marketplace", "resource-marketplace"), item("Knowledge Hub", "knowledge-hub"), item("Capacity Building", "capacity-building"), item("Tools & Templates", "tools-templates"), item("Asset Library", "asset-library"), item("Community Fund", "community-fund"), item("Impact Portfolio", "impact-portfolio")] },
  { path: "/governance", label: "Governance", title: "KINGDOM GOVERNANCE", subtitle: "Accountable. Transparent. Aligned with eternal values.", heading: "Governance Navigation", icon: Crown, items: [item("Governance Dashboard"), item("Ethics & Accountability", "ethics-accountability"), item("Transparency Ledger", "transparency-ledger"), item("Policies & Standards", "policies-standards"), item("Board Oversight", "board-oversight"), item("Stakeholder Engagement", "stakeholder-engagement")] },
];

export function sectionForPath(pathname: string) {
  if (pathname === "/") return PLATFORM_SECTIONS[0];
  return PLATFORM_SECTIONS.find((section) => section.path !== "/" && (pathname === section.path || pathname.startsWith(`${section.path}/`)));
}

export function itemPath(section: PlatformSection, navItem: PlatformNavItem) {
  return navItem.slug ? `${section.path}/${navItem.slug}` : section.path;
}

export function itemForPath(section: PlatformSection, pathname: string) {
  return section.items.find((navItem) => itemPath(section, navItem) === pathname);
}