/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StewardshipRouteImport } from './routes/stewardship'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as IntelligenceRouteImport } from './routes/intelligence'
import { Route as InnovationRouteImport } from './routes/innovation'
import { Route as InfrastructureRouteImport } from './routes/infrastructure'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as HealthRouteImport } from './routes/health'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as GospelCoreRouteImport } from './routes/gospel-core'
import { Route as FundingRouteImport } from './routes/funding'
import { Route as EducationRouteImport } from './routes/education'
import { Route as AiAutomationRouteImport } from './routes/ai-automation'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PeopleIndexRouteImport } from './routes/people.index'
import { Route as PeopleTrainingRouteImport } from './routes/people.training'
import { Route as PeopleTestimoniesRouteImport } from './routes/people.testimonies'
import { Route as PeoplePathwaysRouteImport } from './routes/people.pathways'
import { Route as PeopleMilestonesRouteImport } from './routes/people.milestones'
import { Route as PeopleMentorshipRouteImport } from './routes/people.mentorship'
import { Route as PeopleJourneyRouteImport } from './routes/people.journey'
import { Route as PeopleGroupsRouteImport } from './routes/people.groups'
import { Route as PeopleCareRouteImport } from './routes/people.care'
import { Route as PeopleAssignmentsRouteImport } from './routes/people.assignments'

const StewardshipRoute = StewardshipRouteImport.update({
  id: '/stewardship',
  path: '/stewardship',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceRoute = IntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const InnovationRoute = InnovationRouteImport.update({
  id: '/innovation',
  path: '/innovation',
  getParentRoute: () => rootRouteImport,
} as any)
const InfrastructureRoute = InfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const GospelCoreRoute = GospelCoreRouteImport.update({
  id: '/gospel-core',
  path: '/gospel-core',
  getParentRoute: () => rootRouteImport,
} as any)
const FundingRoute = FundingRouteImport.update({
  id: '/funding',
  path: '/funding',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationRoute = EducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAutomationRoute = AiAutomationRouteImport.update({
  id: '/ai-automation',
  path: '/ai-automation',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleIndexRoute = PeopleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PeopleRoute,
} as any)
const PeopleTrainingRoute = PeopleTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => PeopleRoute,
} as any)
const PeopleTestimoniesRoute = PeopleTestimoniesRouteImport.update({
  id: '/testimonies',
  path: '/testimonies',
  getParentRoute: () => PeopleRoute,
} as any)
const PeoplePathwaysRoute = PeoplePathwaysRouteImport.update({
  id: '/pathways',
  path: '/pathways',
  getParentRoute: () => PeopleRoute,
} as any)
const PeopleMilestonesRoute = PeopleMilestonesRouteImport.update({
  id: '/milestones',
  path: '/milestones',
  getParentRoute: () => PeopleRoute,
} as any)
const PeopleMentorshipRoute = PeopleMentorshipRouteImport.update({
  id: '/mentorship',
  path: '/mentorship',
  getParentRoute: () => PeopleRoute,
} as any)
const PeopleJourneyRoute = PeopleJourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => PeopleRoute,
} as any)
const PeopleGroupsRoute = PeopleGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => PeopleRoute,
} as any)
const PeopleCareRoute = PeopleCareRouteImport.update({
  id: '/care',
  path: '/care',
  getParentRoute: () => PeopleRoute,
} as any)
const PeopleAssignmentsRoute = PeopleAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => PeopleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/ai-automation': typeof AiAutomationRoute
  '/education': typeof EducationRoute
  '/funding': typeof FundingRoute
  '/gospel-core': typeof GospelCoreRoute
  '/governance': typeof GovernanceRoute
  '/health': typeof HealthRoute
  '/impact': typeof ImpactRoute
  '/infrastructure': typeof InfrastructureRoute
  '/innovation': typeof InnovationRoute
  '/intelligence': typeof IntelligenceRoute
  '/partners': typeof PartnersRoute
  '/people': typeof PeopleRouteWithChildren
  '/platform': typeof PlatformRoute
  '/security': typeof SecurityRoute
  '/stewardship': typeof StewardshipRoute
  '/people/assignments': typeof PeopleAssignmentsRoute
  '/people/care': typeof PeopleCareRoute
  '/people/groups': typeof PeopleGroupsRoute
  '/people/journey': typeof PeopleJourneyRoute
  '/people/mentorship': typeof PeopleMentorshipRoute
  '/people/milestones': typeof PeopleMilestonesRoute
  '/people/pathways': typeof PeoplePathwaysRoute
  '/people/testimonies': typeof PeopleTestimoniesRoute
  '/people/training': typeof PeopleTrainingRoute
  '/people/': typeof PeopleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/ai-automation': typeof AiAutomationRoute
  '/education': typeof EducationRoute
  '/funding': typeof FundingRoute
  '/gospel-core': typeof GospelCoreRoute
  '/governance': typeof GovernanceRoute
  '/health': typeof HealthRoute
  '/impact': typeof ImpactRoute
  '/infrastructure': typeof InfrastructureRoute
  '/innovation': typeof InnovationRoute
  '/intelligence': typeof IntelligenceRoute
  '/partners': typeof PartnersRoute
  '/platform': typeof PlatformRoute
  '/security': typeof SecurityRoute
  '/stewardship': typeof StewardshipRoute
  '/people/assignments': typeof PeopleAssignmentsRoute
  '/people/care': typeof PeopleCareRoute
  '/people/groups': typeof PeopleGroupsRoute
  '/people/journey': typeof PeopleJourneyRoute
  '/people/mentorship': typeof PeopleMentorshipRoute
  '/people/milestones': typeof PeopleMilestonesRoute
  '/people/pathways': typeof PeoplePathwaysRoute
  '/people/testimonies': typeof PeopleTestimoniesRoute
  '/people/training': typeof PeopleTrainingRoute
  '/people': typeof PeopleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/ai-automation': typeof AiAutomationRoute
  '/education': typeof EducationRoute
  '/funding': typeof FundingRoute
  '/gospel-core': typeof GospelCoreRoute
  '/governance': typeof GovernanceRoute
  '/health': typeof HealthRoute
  '/impact': typeof ImpactRoute
  '/infrastructure': typeof InfrastructureRoute
  '/innovation': typeof InnovationRoute
  '/intelligence': typeof IntelligenceRoute
  '/partners': typeof PartnersRoute
  '/people': typeof PeopleRouteWithChildren
  '/platform': typeof PlatformRoute
  '/security': typeof SecurityRoute
  '/stewardship': typeof StewardshipRoute
  '/people/assignments': typeof PeopleAssignmentsRoute
  '/people/care': typeof PeopleCareRoute
  '/people/groups': typeof PeopleGroupsRoute
  '/people/journey': typeof PeopleJourneyRoute
  '/people/mentorship': typeof PeopleMentorshipRoute
  '/people/milestones': typeof PeopleMilestonesRoute
  '/people/pathways': typeof PeoplePathwaysRoute
  '/people/testimonies': typeof PeopleTestimoniesRoute
  '/people/training': typeof PeopleTrainingRoute
  '/people/': typeof PeopleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/ai-automation'
    | '/education'
    | '/funding'
    | '/gospel-core'
    | '/governance'
    | '/health'
    | '/impact'
    | '/infrastructure'
    | '/innovation'
    | '/intelligence'
    | '/partners'
    | '/people'
    | '/platform'
    | '/security'
    | '/stewardship'
    | '/people/assignments'
    | '/people/care'
    | '/people/groups'
    | '/people/journey'
    | '/people/mentorship'
    | '/people/milestones'
    | '/people/pathways'
    | '/people/testimonies'
    | '/people/training'
    | '/people/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/ai-automation'
    | '/education'
    | '/funding'
    | '/gospel-core'
    | '/governance'
    | '/health'
    | '/impact'
    | '/infrastructure'
    | '/innovation'
    | '/intelligence'
    | '/partners'
    | '/platform'
    | '/security'
    | '/stewardship'
    | '/people/assignments'
    | '/people/care'
    | '/people/groups'
    | '/people/journey'
    | '/people/mentorship'
    | '/people/milestones'
    | '/people/pathways'
    | '/people/testimonies'
    | '/people/training'
    | '/people'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/ai-automation'
    | '/education'
    | '/funding'
    | '/gospel-core'
    | '/governance'
    | '/health'
    | '/impact'
    | '/infrastructure'
    | '/innovation'
    | '/intelligence'
    | '/partners'
    | '/people'
    | '/platform'
    | '/security'
    | '/stewardship'
    | '/people/assignments'
    | '/people/care'
    | '/people/groups'
    | '/people/journey'
    | '/people/mentorship'
    | '/people/milestones'
    | '/people/pathways'
    | '/people/testimonies'
    | '/people/training'
    | '/people/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AiAutomationRoute: typeof AiAutomationRoute
  EducationRoute: typeof EducationRoute
  FundingRoute: typeof FundingRoute
  GospelCoreRoute: typeof GospelCoreRoute
  GovernanceRoute: typeof GovernanceRoute
  HealthRoute: typeof HealthRoute
  ImpactRoute: typeof ImpactRoute
  InfrastructureRoute: typeof InfrastructureRoute
  InnovationRoute: typeof InnovationRoute
  IntelligenceRoute: typeof IntelligenceRoute
  PartnersRoute: typeof PartnersRoute
  PeopleRoute: typeof PeopleRouteWithChildren
  PlatformRoute: typeof PlatformRoute
  SecurityRoute: typeof SecurityRoute
  StewardshipRoute: typeof StewardshipRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stewardship': {
      id: '/stewardship'
      path: '/stewardship'
      fullPath: '/stewardship'
      preLoaderRoute: typeof StewardshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence': {
      id: '/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof IntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innovation': {
      id: '/innovation'
      path: '/innovation'
      fullPath: '/innovation'
      preLoaderRoute: typeof InnovationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure': {
      id: '/infrastructure'
      path: '/infrastructure'
      fullPath: '/infrastructure'
      preLoaderRoute: typeof InfrastructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gospel-core': {
      id: '/gospel-core'
      path: '/gospel-core'
      fullPath: '/gospel-core'
      preLoaderRoute: typeof GospelCoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funding': {
      id: '/funding'
      path: '/funding'
      fullPath: '/funding'
      preLoaderRoute: typeof FundingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education': {
      id: '/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof EducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-automation': {
      id: '/ai-automation'
      path: '/ai-automation'
      fullPath: '/ai-automation'
      preLoaderRoute: typeof AiAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/': {
      id: '/people/'
      path: '/'
      fullPath: '/people/'
      preLoaderRoute: typeof PeopleIndexRouteImport
      parentRoute: typeof PeopleRoute
    }
    '/people/training': {
      id: '/people/training'
      path: '/training'
      fullPath: '/people/training'
      preLoaderRoute: typeof PeopleTrainingRouteImport
      parentRoute: typeof PeopleRoute
    }
    '/people/testimonies': {
      id: '/people/testimonies'
      path: '/testimonies'
      fullPath: '/people/testimonies'
      preLoaderRoute: typeof PeopleTestimoniesRouteImport
      parentRoute: typeof PeopleRoute
    }
    '/people/pathways': {
      id: '/people/pathways'
      path: '/pathways'
      fullPath: '/people/pathways'
      preLoaderRoute: typeof PeoplePathwaysRouteImport
      parentRoute: typeof PeopleRoute
    }
    '/people/milestones': {
      id: '/people/milestones'
      path: '/milestones'
      fullPath: '/people/milestones'
      preLoaderRoute: typeof PeopleMilestonesRouteImport
      parentRoute: typeof PeopleRoute
    }
    '/people/mentorship': {
      id: '/people/mentorship'
      path: '/mentorship'
      fullPath: '/people/mentorship'
      preLoaderRoute: typeof PeopleMentorshipRouteImport
      parentRoute: typeof PeopleRoute
    }
    '/people/journey': {
      id: '/people/journey'
      path: '/journey'
      fullPath: '/people/journey'
      preLoaderRoute: typeof PeopleJourneyRouteImport
      parentRoute: typeof PeopleRoute
    }
    '/people/groups': {
      id: '/people/groups'
      path: '/groups'
      fullPath: '/people/groups'
      preLoaderRoute: typeof PeopleGroupsRouteImport
      parentRoute: typeof PeopleRoute
    }
    '/people/care': {
      id: '/people/care'
      path: '/care'
      fullPath: '/people/care'
      preLoaderRoute: typeof PeopleCareRouteImport
      parentRoute: typeof PeopleRoute
    }
    '/people/assignments': {
      id: '/people/assignments'
      path: '/assignments'
      fullPath: '/people/assignments'
      preLoaderRoute: typeof PeopleAssignmentsRouteImport
      parentRoute: typeof PeopleRoute
    }
  }
}

interface PeopleRouteChildren {
  PeopleAssignmentsRoute: typeof PeopleAssignmentsRoute
  PeopleCareRoute: typeof PeopleCareRoute
  PeopleGroupsRoute: typeof PeopleGroupsRoute
  PeopleJourneyRoute: typeof PeopleJourneyRoute
  PeopleMentorshipRoute: typeof PeopleMentorshipRoute
  PeopleMilestonesRoute: typeof PeopleMilestonesRoute
  PeoplePathwaysRoute: typeof PeoplePathwaysRoute
  PeopleTestimoniesRoute: typeof PeopleTestimoniesRoute
  PeopleTrainingRoute: typeof PeopleTrainingRoute
  PeopleIndexRoute: typeof PeopleIndexRoute
}

const PeopleRouteChildren: PeopleRouteChildren = {
  PeopleAssignmentsRoute: PeopleAssignmentsRoute,
  PeopleCareRoute: PeopleCareRoute,
  PeopleGroupsRoute: PeopleGroupsRoute,
  PeopleJourneyRoute: PeopleJourneyRoute,
  PeopleMentorshipRoute: PeopleMentorshipRoute,
  PeopleMilestonesRoute: PeopleMilestonesRoute,
  PeoplePathwaysRoute: PeoplePathwaysRoute,
  PeopleTestimoniesRoute: PeopleTestimoniesRoute,
  PeopleTrainingRoute: PeopleTrainingRoute,
  PeopleIndexRoute: PeopleIndexRoute,
}

const PeopleRouteWithChildren =
  PeopleRoute._addFileChildren(PeopleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AiAutomationRoute: AiAutomationRoute,
  EducationRoute: EducationRoute,
  FundingRoute: FundingRoute,
  GospelCoreRoute: GospelCoreRoute,
  GovernanceRoute: GovernanceRoute,
  HealthRoute: HealthRoute,
  ImpactRoute: ImpactRoute,
  InfrastructureRoute: InfrastructureRoute,
  InnovationRoute: InnovationRoute,
  IntelligenceRoute: IntelligenceRoute,
  PartnersRoute: PartnersRoute,
  PeopleRoute: PeopleRouteWithChildren,
  PlatformRoute: PlatformRoute,
  SecurityRoute: SecurityRoute,
  StewardshipRoute: StewardshipRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
